language: python
python:
- 2.7.10
install: pip install -r requirements.txt

env:
  global:
  - SAUCE_USERNAME=anveshmalhotra
  - SAUCE_ACCESS_KEY=6d27c807-1c2b-41e4-9411-73944a17211e

script: py.test -s -n 8 tests

notifications:
  email:
    recipients:
      - anvesh.malhotra@asu.edu
      - anvesh091030ece@gmail.com
      - gsypolt@gannett.com
      - mhist@usatoday.com
      - ebursch@gannett.com
      - klucas@gannett.com
    on_success: always 
    on_failure: always 