language: python
python:
- 2.7.10
install: pip install -r requirements.txt
script: py.test -n 8 src.common
env:
  global:
  - SAUCE_USERNAME=anveshmalhotra
addons:
  jwt:
    secure: 6d27c807-1c2b-41e4-9411-73944a17211e

    
