language: python
python:
  - "2.7"  
  - "3.0"
install: "pip install -r requirements.txt"  
addons:
  sauce_connect:
    username: "anveshmalhotra"
    access_key: "6d27c807-1c2b-41e4-9411-73944a17211e"
script:
 - pytest -d --tx 3*popen//python=python2.7
notifications:
  email: 
    - amalho14@asu.edu
    
